version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: b5d9f8h7
      MYSQL_DATABASE: hackaton
      MYSQL_USER: root
      MYSQL_PASSWORD: b5d9f8h7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: